### ISSUE TITLE
not compiling

### ISSUE THREAD

**Issue by randogoth** [tstrausb/XKeys-Library-for-Arduino#1]
hi! unfortunately i cannot compile your library. I added the required USB Shield lib.

I get the error that "HID" is not defined. The file "HID.h" cannot be found. 

In which library is HID defined?

Cheers!

**Comment by tstrausb** [comment]
Most likely, you need to download the older version of the USB host shield library. Mine has not yet been updated to work with 3.0; you should be able to download 2.0 from Circuits @ Home.

On Jun 20, 2016, at 9:01 AM, kflux <notifications@github.com<mailto:notifications@github.com>> wrote:

hi! unfortunately i cannot compile your library. I added the required USB Shield lib.

I get the error that "HID" is not defined. The file "HID.h" cannot be found.

In which library is HID defined?

Cheers!

##

**Comment by randogoth** [comment]
i am using version 2.0 of the lib. I still get the same error:

```
XKeys-Library-for-Arduino/hidxkeysrptparser.h:60:21: error: 'HID' has not been declared
  virtual void Parse(HID *hid, bool is_rpt_id, uint8_t len, uint8_t *buf);
```

**Comment by tstrausb** [comment]
Hi flux,

Send me your sketch and I'll take a look...

Thanks,
Tom

On Jun 28, 2016, at 5:08 AM, kflux <notifications@github.com<mailto:notifications@github.com>> wrote:

i am using version 2.0 of the lib. I still get the same error:

XKeys-Library-for-Arduino/hidxkeysrptparser.h:60:21: error: 'HID' has not been declared
  virtual void Parse(HID *hid, bool is_rpt_id, uint8_t len, uint8_t *buf);

##

**Comment by randogoth** [comment]
no sketch yet. just tried to compile the libraries. HID and Usb Shield 2.0 libs are present and found in the path. But the HID class declaration can't be found. See my last post. 

```
#include <hidxkeysrptparser.h>

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
```

**Comment by tstrausb** [comment]
Aha,

That's why; the library doesn't declare an HID object. The sketch has to. If the library takes anything by reference, you have to declare it yourself.

Try compiling one of the examples and make sure that works. Though there is some info in them that you'll have to enter.

Tom

On Jun 28, 2016, at 10:48 AM, kflux <notifications@github.com<mailto:notifications@github.com>> wrote:

no sketch yet. just tried to compile the libraries.

#include <hidxkeysrptparser.h>

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}

##

**Comment by randogoth** [comment]
ooh! allright. thanks!

**Comment by randogoth** [comment]
none of the examples compile. same error. what am i missing?

`XKeys-Library-for-Arduino/hidxkeysrptparser.h:60:21: error: 'HID' has not been declared
  virtual void Parse(HID *hid, bool is_rpt_id, uint8_t len, uint8_t *buf);`

**Comment by tstrausb** [comment]
Well that is odd! Send me an exact copy of the example that won't compile.
- Tom

**Comment by randogoth** [comment]
copied and pasted the code from [this example](https://github.com/tstrausb/XKeys-Library-for-Arduino/blob/master/examples/xkeys_demo/xkeys_demo.ino) and compiled. Got the error for hidxkeysrptparser.h that 'hid.h' cannot be found. So I went into hidxkeysrptparser.h and renamed the include to "HID.h" which i know exists but the next error i get is the one i mentioned before that 'HID' has not been declared.

**Comment by HotMachete** [comment]
Was there ever a solution found for this?  I'm getting the same problem.  None of the example sketches compile.  It seems to be that the example sketches and hidxkeysrptparser.h are trying to include the library 'hid.h', however this library isn't part of USB_Host_Shield_2.0 nor is it part of the current Arduino IDE.  The current IDE contains 'HID.h', however if you edit the example sketches and hidxkeysrptparser.h to include 'HID.h' instead of 'hid.h", you get the error that kflux mentioned above.

**Comment by HotMachete** [comment]
Nevermind, I found the fork by JasonRivers that has everything updated for USB_Host_Shield_2.0.  That fixes the compiling issue.

https://github.com/JasonRivers/XKeys-Library-for-Arduino/tree/USBHID-fixes

**Comment by JasonRivers** [comment]
This is also in PR #2
